name: Documentation Check

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: .markdownlint.jsonc

      - name: Check File Size
        run: |
          for file in $(find docs -name "*.md"); do
            size=$(wc -c < "$file")
            if [ $size -gt 10000 ]; then
              echo "Warning: $file is larger than 10000 bytes"
              exit 1
            fi
          done
      - name: Generate SBOM
        run: |
          if [ -f "package.json" ]; then
            npm install -g @cyclonedx/cyclonedx-npm
            cyclonedx-npm --output-file docs/standards/sbom/sbom.xml
            cyclonedx-npm --output-file docs/standards/sbom/sbom.json --format json
          else
            echo "Skipping SBOM generation: package.json not found"
          fi
      - name: Check Language Consistency
        run: |
          echo "=== Checking language file pairs ==="
          missing_files=""
          
          # 日本語版に対応する英語版の存在チェック
          for file in $(find docs -name "*-ja.md"); do
            en_file=${file%-ja.md}.md
            if [ ! -f "$en_file" ]; then
              echo "Warning: English version missing for $file"
              missing_files="$missing_files\n- English version missing for: $file"
            fi
          done
          
          # 英語版に対応する日本語版の存在チェック
          for file in $(find docs -name "*.md" ! -name "*-ja.md" ! -name "README.md" ! -name "CHANGELOG.md" ! -name "SUMMARY.md"); do
            ja_file=${file%.md}-ja.md
            if [ ! -f "$ja_file" ]; then
              echo "Warning: Japanese version missing for $file"
              missing_files="$missing_files\n- Japanese version missing for: $file"
            fi
          done
          
          # 警告があれば表示（エラーにはしない）
          if [ -n "$missing_files" ]; then
            echo -e "\nLanguage consistency warnings:$missing_files"
          fi