name: Guidelines Size Check

on:
  pull_request:
    paths:
      - 'ai/context/summary.md'
      - 'ai/context/summary-ja.md'
  push:
    branches:
      - main
    paths:
      - 'ai/context/summary.md'
      - 'ai/context/summary-ja.md'

jobs:
  check-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check summary.md size
        run: |
          # Check English version
          if [ -f "ai/context/summary.md" ]; then
            echo "Checking ai/context/summary.md..."
            FILE_PATH="ai/context/summary.md"
            
            # Get file stats
            CHAR_COUNT=$(wc -c < "$FILE_PATH")
            WORD_COUNT=$(wc -w < "$FILE_PATH")
            LINE_COUNT=$(wc -l < "$FILE_PATH")
            
            echo "File: $FILE_PATH"
            echo "Character count: $CHAR_COUNT"
            echo "Word count: $WORD_COUNT"
            echo "Line count: $LINE_COUNT"
            
            # More accurate token estimation for mixed EN/JA content
            # For English: ~1 token per 4 characters
            # For Japanese: ~1 token per 2 characters
            # Mixed content: use character-based estimation
            TOKEN_COUNT=$(( CHAR_COUNT / 3 ))
            
            echo "Estimated token count: $TOKEN_COUNT"
            
            # Extract MAX_TOKENS from file header if present
            MAX_TOKENS=$(grep -o 'MAX_TOKENS: [0-9]*' "$FILE_PATH" | grep -o '[0-9]*' || echo "2000")
            echo "Max allowed tokens: $MAX_TOKENS"
            
            if [ "$TOKEN_COUNT" -gt "$MAX_TOKENS" ]; then
              echo "::error::$FILE_PATH exceeds $MAX_TOKENS tokens (estimated: $TOKEN_COUNT)"
              echo "Please reduce the file size to stay within the token limit"
              exit 1
            else
              echo "✅ File is within the $MAX_TOKENS token limit"
            fi
          fi
          
          # Check Japanese version
          if [ -f "ai/context/summary-ja.md" ]; then
            echo ""
            echo "Checking ai/context/summary-ja.md..."
            FILE_PATH="ai/context/summary-ja.md"
            
            # Get file stats
            CHAR_COUNT=$(wc -c < "$FILE_PATH")
            WORD_COUNT=$(wc -w < "$FILE_PATH")
            LINE_COUNT=$(wc -l < "$FILE_PATH")
            
            echo "File: $FILE_PATH"
            echo "Character count: $CHAR_COUNT"
            echo "Word count: $WORD_COUNT"
            echo "Line count: $LINE_COUNT"
            
            # Japanese content: ~1 token per 2 characters
            TOKEN_COUNT=$(( CHAR_COUNT / 2 ))
            
            echo "Estimated token count: $TOKEN_COUNT"
            
            # Extract MAX_TOKENS from file header if present
            MAX_TOKENS=$(grep -o 'MAX_TOKENS: [0-9]*' "$FILE_PATH" | grep -o '[0-9]*' || echo "2000")
            echo "Max allowed tokens: $MAX_TOKENS"
            
            if [ "$TOKEN_COUNT" -gt "$MAX_TOKENS" ]; then
              echo "::error::$FILE_PATH exceeds $MAX_TOKENS tokens (estimated: $TOKEN_COUNT)"
              echo "Please reduce the file size to stay within the token limit"
              exit 1
            else
              echo "✅ File is within the $MAX_TOKENS token limit"
            fi
          fi
