name: Markdown Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.mlc_config.json'

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check Markdown Links
        run: markdown-link-check $(find . -name "*.md") -c .mlc_config.json 